local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("statusbar", "Aluminium", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Aluminium]])
LSM:Register("statusbar", "Armory", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Armory]])
LSM:Register("statusbar", "BantoBar", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\BantoBar]])
LSM:Register("statusbar", "Bars", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Bars]])
LSM:Register("statusbar", "Bumps", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Bumps]])
LSM:Register("statusbar", "Button", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Button]])
LSM:Register("statusbar", "Charcoal", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Charcoal]])
LSM:Register("statusbar", "Cilo", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Cilo]])
LSM:Register("statusbar", "Cloud", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Cloud]])
LSM:Register("statusbar", "Combo", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Combo]])
LSM:Register("statusbar", "Comet", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Comet]])
LSM:Register("statusbar", "Dabs", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Dabs]])
LSM:Register("statusbar", "Details", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Details]])
LSM:Register("statusbar", "Diagonal", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Diagonal]])
LSM:Register("statusbar", "Falumn", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Falumn]])
LSM:Register("statusbar", "Fifths", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Fifths]])
LSM:Register("statusbar", "Flat", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Flat]])
LSM:Register("statusbar", "Fourths", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Fourths]])
LSM:Register("statusbar", "Frost", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Frost]])
LSM:Register("statusbar", "Glamour", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glamour]])
LSM:Register("statusbar", "Glamour2", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glamour2]])
LSM:Register("statusbar", "Glamour3", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glamour3]])
LSM:Register("statusbar", "Glamour4", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glamour4]])
LSM:Register("statusbar", "Glamour5", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glamour5]])
LSM:Register("statusbar", "Glamour6", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glamour6]])
LSM:Register("statusbar", "Glamour7", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glamour7]])
LSM:Register("statusbar", "Glass", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glass]])
LSM:Register("statusbar", "Glaze", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glaze]])
LSM:Register("statusbar", "Glaze2", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Glaze2]])
LSM:Register("statusbar", "Gloss", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Gloss]])
LSM:Register("statusbar", "Graphite", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Graphite]])
LSM:Register("statusbar", "Grid", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Grid]])
LSM:Register("statusbar", "Hatched", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Hatched]])
LSM:Register("statusbar", "Healbot", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Healbot]])
LSM:Register("statusbar", "LiteStep", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\LiteStep]])
LSM:Register("statusbar", "LiteStepLite", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\LiteStepLite]])
LSM:Register("statusbar", "Lyfe", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Lyfe]])
LSM:Register("statusbar", "Melli", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Melli]])
LSM:Register("statusbar", "MelliDark", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\MelliDark]])
LSM:Register("statusbar", "Minimalist", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Minimalist]])
LSM:Register("statusbar", "Otravi", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Otravi]])
LSM:Register("statusbar", "Outline", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Outline]])
LSM:Register("statusbar", "Perl2", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Perl2]])
LSM:Register("statusbar", "Pill", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Pill]])
LSM:Register("statusbar", "Rain", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Rain]])
LSM:Register("statusbar", "Rocks", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Rocks]])
LSM:Register("statusbar", "Round", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Round]])
LSM:Register("statusbar", "Ruben", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Ruben]])
LSM:Register("statusbar", "Runes", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Runes]])
LSM:Register("statusbar", "Serenity", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Serenity]])
LSM:Register("statusbar", "Skewed", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Skewed]])
LSM:Register("statusbar", "Smooth v2", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Smoothv2]])
LSM:Register("statusbar", "Smooth", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Smooth]])
LSM:Register("statusbar", "Smudge", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Smudge]])
LSM:Register("statusbar", "Striped", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Striped]])
LSM:Register("statusbar", "Tube", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Tube]])
LSM:Register("statusbar", "TukTex", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\TukTex]])
LSM:Register("statusbar", "Water", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Water]])
LSM:Register("statusbar", "Wglass", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Wglass]])
LSM:Register("statusbar", "Wisps", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Wisps]])
LSM:Register("statusbar", "Flatt", [[Interface\AddOns\sNamePlates\Media\Textures\Statusbar\Flatt]])

LSM:Register("font", "ABF", [[Interface\AddOns\sNamePlates\Media\Fonts\ABF.ttf]])
LSM:Register("font", "Accidental Presidency", [[Interface\AddOns\sNamePlates\Media\Fonts\Accidental Presidency.ttf]])
LSM:Register("font", "Action Man", [[Interface\AddOns\sNamePlates\Media\Fonts\ActionMan.ttf]])
LSM:Register("font", "Adventure", [[Interface\AddOns\sNamePlates\Media\Fonts\Adventure.ttf]])
LSM:Register("font", "Continuum Medium", [[Interface\AddOns\sNamePlates\Media\Fonts\ContinuumMedium.ttf]])
LSM:Register("font", "Diablo", [[Interface\AddOns\sNamePlates\Media\Fonts\Diablo.ttf]])
LSM:Register("font", "DomyoujiRegular", [[Interface\AddOns\sNamePlates\Media\Fonts\DomyoujiRegular.ttf]])
LSM:Register("font", "Die Die Die!", [[Interface\AddOns\sNamePlates\Media\Fonts\DieDieDie.ttf]])
LSM:Register("font", "Dsdig", [[Interface\AddOns\sNamePlates\Media\Fonts\Dsdig.ttf]])
LSM:Register("font", "Expressway", [[Interface\AddOns\sNamePlates\Media\Fonts\Expressway.ttf]])
LSM:Register("font", "Forced Square", [[Interface\AddOns\sNamePlates\Media\Fonts\FORCED SQUARE.ttf]])
LSM:Register("font", "Hooge", [[Interface\AddOns\sNamePlates\Media\Fonts\Hooge.TTF]])
LSM:Register("font", "Homespun", [[Interface\AddOns\sNamePlates\Media\Fonts\Homespun.ttf]])
LSM:Register("font", "PT Sans Narrow", [[Interface\AddOns\sNamePlates\Media\Fonts\PTSansNarrow.ttf]])
LSM:Register("font", "Seagram", [[Interface\AddOns\sNamePlates\Media\Fonts\Seagram.ttf]])
LSM:Register("font", "Vipnagorgia", [[Interface\AddOns\sNamePlates\Media\Fonts\Vipnagorgiallarg.ttf]])
LSM:Register("font", "yanone", [[Interface\AddOns\sNamePlates\Media\Fonts\yanone.ttf]])